// Purchase Order — rendered as an HTML page (printable via browser print-to-PDF).
// Zero JSX runtime dependencies. The route at /api/po/:poNumber serves these.
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

export interface PurchaseOrder {
  poNumber: string;
  supplierName: string;
  supplierPhone: string | null;
  lines: { productName: string; qty: number; unitPrice: number; amount: number }[];
  totalInr: number;
  issuedAt: Date;
}

const inr = (n: number) => `₹${n.toLocaleString('en-IN')}`;

export async function renderPoPdf(po: PurchaseOrder): Promise<Buffer> {
  mkdirSync('./data/pos', { recursive: true });

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>${po.poNumber} — Purchase Order | Otto</title>
<style>
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:system-ui,-apple-system,Helvetica,Arial,sans-serif;font-size:12px;color:#1a1a1a;padding:40px;max-width:700px;margin:0 auto}
h1{font-size:22px;font-weight:700;color:#b45309}
.sub{color:#555;margin-top:2px;margin-bottom:24px}
h2{font-size:16px;margin:20px 0 6px}
table{width:100%;border-collapse:collapse}
th{text-align:left;border-bottom:2px solid #333;padding:6px 4px;font-size:11px;text-transform:uppercase;color:#555}
td{padding:6px 4px;border-bottom:1px solid #ddd;font-variant-numeric:tabular-nums}
.r{text-align:right}
.total{margin-top:10px;font-size:18px;font-weight:700;text-align:right}
.foot{margin-top:48px;font-size:10px;color:#777}
@media print{body{padding:0}}
</style>
</head>
<body>
<h1>Priya's Fashion <span style="color:#b45309">· Purchase Order</span></h1>
<p class="sub">Johari Bazar, Jaipur · Drafted by Otto, approved by owner</p>
<h2>${po.poNumber}</h2>
<p class="sub">Date: ${po.issuedAt.toISOString().slice(0, 10)} · Supplier: ${po.supplierName}${po.supplierPhone ? ` · ${po.supplierPhone}` : ''}</p>
<table>
<thead><tr><th>Product</th><th class="r">Qty</th><th class="r">Unit price</th><th class="r">Amount</th></tr></thead>
<tbody>
${po.lines.map((l) => `<tr><td>${l.productName}</td><td class="r">${l.qty}</td><td class="r">${inr(l.unitPrice)}</td><td class="r">${inr(l.amount)}</td></tr>`).join('\n')}
</tbody>
</table>
<p class="total">Total: ${inr(po.totalInr)}</p>
<p class="foot">Generated by Otto — every step of this order is logged and inspectable in the agent activity trace.</p>
</body>
</html>`;

  writeFileSync(join('./data/pos', `${po.poNumber}.html`), html);
  return Buffer.from(html);
}
